apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-token
  namespace: ch14-team-a
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: hf-token
    creationPolicy: Owner
  data:
  - secretKey: HF_TOKEN
    remoteRef:
      key: ch14-team-a-hf-token
