apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-team-a.yaml
  - namespace-team-b.yaml
  - resourcequota-team-a.yaml
  - resourcequota-team-b.yaml
  - limitrange-team-a.yaml
  - limitrange-team-b.yaml
