apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/dra
patches:
  - target:
      kind: (Job|Deployment)
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          eks.amazonaws.com/capacityType: SPOT
  - target:
      kind: Pod
    patch: |-
      - op: add
        path: /spec/nodeSelector
        value:
          eks.amazonaws.com/capacityType: SPOT
