apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount-pipelines-runner.yaml
  - pvc-pipeline-artifacts.yaml
  - workflowtemplate-train-pipeline.yaml
