apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipelines-runner
  namespace: ch15-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipelines-runner
  namespace: ch15-pipelines
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtemplates", "workflowtaskresults"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipelines-runner
  namespace: ch15-pipelines
subjects:
- kind: ServiceAccount
  name: pipelines-runner
  namespace: ch15-pipelines
roleRef:
  kind: Role
  name: pipelines-runner
  apiGroup: rbac.authorization.k8s.io
