apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/mig
patches:
  - target:
      kind: Deployment
      name: mig-demo
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          cloud.google.com/gke-spot: "true"
          cloud.google.com/gke-accelerator: nvidia-tesla-a100
          cloud.google.com/gke-gpu-partition-size: 1g.5gb
