apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# First: az aks nodepool created with the label from create-nodepool-share.sh
# (SHARE_MODE=time-sliced-4, the default).
resources:
  - ../../common/timeslicing
patches:
  - target:
      kind: Deployment
      name: timeslice-demo
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.azure.com/scalesetpriority: spot
          nvidia.com/device-plugin.config: time-sliced-4
      - op: add
        path: /spec/template/spec/tolerations/-
        value:
          key: kubernetes.azure.com/scalesetpriority   # added automatically by AKS on spot pools
          operator: Equal
          value: spot
          effect: NoSchedule
