apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/timeslicing
patches:
  - target:
      kind: Deployment
      name: timeslice-demo
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          eks.amazonaws.com/capacityType: SPOT
          nvidia.com/gpu.sharing-strategy: time-slicing   # set by GPU Feature Discovery
