apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-models
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap          # one EFS access point per PVC
  fileSystemId: REPLACED_BY_KUSTOMIZE
  directoryPerms: "755"
reclaimPolicy: Delete
volumeBindingMode: Immediate
